name: Fastlane build

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    name: Release binary and push it to AppStore
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
      - name: Resolve Swift packages
        run: xcodebuild -resolvePackageDependencies -project "Kalender Puasa.xcodeproj"
      - name: Create GoogleService-Info.plist
        env:
          GOOGLE_SERVICE_INFO: ${{ secrets.GOOGLE_SERVICE_INFO }}
        run: printf '%s' "$GOOGLE_SERVICE_INFO" > "./Kalender Puasa/GoogleService-Info.plist"
      - uses: maierj/fastlane-action@v2.3.0
        with:
          lane: 'build'
          verbose: true
        env:
          APPLE_KEY_ID: '${{ secrets.APPLE_KEY_ID }}'
          APPLE_ISSUER_ID: '${{ secrets.APPLE_ISSUER_ID }}'
          APPLE_KEY_CONTENT: '${{ secrets.APPLE_KEY_CONTENT }}'
          APPLE_ID: '${{ secrets.APPLE_ID }}'
          ITC_TEAM_ID: '${{ secrets.ITC_TEAM_ID }}'
          TEAM_ID: '${{ secrets.TEAM_ID }}'
          PROVISIONING_PROFILE: '${{ secrets.PROVISIONING_PROFILE }}'
          MATCH_ENVIRONMENT: '${{ secrets.MATCH_ENVIRONMENT }}'
          MATCH_CERTIFICATES_REPO_URL: '${{ secrets.MATCH_CERTIFICATES_REPO_URL }}'
          MATCH_GIT_BASIC_AUTHORIZATION: '${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}'
          MATCH_PASSWORD: '${{ secrets.MATCH_PASSWORD }}'
          TEMP_KEYCHAIN_USER: '${{ secrets.TEMP_KEYCHAIN_USER }}'
          TEMP_KEYCHAIN_PASSWORD: '${{ secrets.TEMP_KEYCHAIN_PASSWORD }}'
